version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_login
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_login
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    ports:
      - "8080:80"
    command: php -S 0.0.0.0:80
